import theme from '../../util/theme';

export const styles = {
  h1: {
    fontFamily: theme.typography.fonts.circularStdBold,
    color: theme.colors.typography.black,
    fontWeight: theme.typography.fontWeights.bold,
    fontSize: theme.typography.fontSizes.xl6,
  },
  h2: {
    fontFamily: theme.typography.fonts.circularStdBold,
    color: theme.colors.typography.black,
    fontWeight: theme.typography.fontWeights.bold,
    fontSize: theme.typography.fontSizes.xl5,
  },
  h3: {
    fontFamily: theme.typography.fonts.circularStdBook,
    color: theme.colors.typography.black,
    fontWeight: theme.typography.fontWeights.normal,
    fontSize: theme.typography.fontSizes.xl2,
  },
  h4: {
    fontFamily: theme.typography.fonts.circularStdBold,
    color: theme.colors.typography.black,
    fontWeight: theme.typography.fontWeights.bold,
    fontSize: theme.typography.fontSizes.xl,
    lineHeight: theme.typography.lineHeights.xl4,
  },
  h5: {
    fontFamily: theme.typography.fonts.circularStdBook,
    color: theme.colors.typography.black,
    fontWeight: theme.typography.fontWeights.normal,
    fontSize: theme.typography.fontSizes.lg,
    lineHeight: theme.typography.lineHeights.xl,
  },
  body1: {
    fontFamily: theme.typography.fonts.circularStdBook,
    color: theme.colors.typography.black,
    fontWeight: theme.typography.fontWeights.normal,
    fontSize: theme.typography.fontSizes.md,
    lineHeight: theme.typography.lineHeights.md,
  },
  body2: {
    fontFamily: theme.typography.fonts.circularStdBook,
    color: theme.colors.typography.black,
    fontWeight: theme.typography.fontWeights.normal,
    fontSize: theme.typography.fontSizes.sm,
  },
  body3: {
    fontFamily: theme.typography.fonts.circularStdBold,
    color: theme.colors.typography.black,
    fontWeight: theme.typography.fontWeights.bold,
    fontSize: theme.typography.fontSizes.xs,
  },
  subtitle1: {
    fontFamily: theme.typography.fonts.circularStdMedium,
    color: theme.colors.typography.black,
    fontWeight: theme.typography.fontWeights.medium,
    fontSize: theme.typography.fontSizes.lg,
    lineHeight: theme.typography.lineHeights.xl,
  },
  subtitle2: {
    fontFamily: theme.typography.fonts.circularStdMedium,
    color: theme.colors.typography.black,
    fontWeight: theme.typography.fontWeights.medium,
    fontSize: theme.typography.fontSizes.md,
    lineHeight: theme.typography.lineHeights.xl,
  },
  button1: {
    fontFamily: theme.typography.fonts.circularStdBold,
    color: theme.colors.typography.black,
    fontWeight: theme.typography.fontWeights.bold,
    fontSize: theme.typography.fontSizes.md,
    lineHeight: theme.typography.lineHeights.xl,
  },
  button2: {
    fontFamily: theme.typography.fonts.circularStdBold,
    color: theme.colors.typography.black,
    fontWeight: theme.typography.fontWeights.bold,
    fontSize: theme.typography.fontSizes.sm,
    lineHeight: theme.typography.lineHeights.xl,
  },
  caption12: {
    fontFamily: theme.typography.fonts.circularStdBook,
    color: theme.colors.typography.secondary,
    fontWeight: theme.typography.fontWeights.normal,
    fontSize: theme.typography.fontSizes.xs,
  },
  navigation: {
    fontFamily: theme.typography.fonts.circularStdBold,
    color: theme.colors.typography.black,
    fontWeight: theme.typography.fontWeights.bold,
    fontSize: theme.typography.fontSizes.xs,
    lineHeight: theme.typography.lineHeights.xl,
  },
  link: {
    fontFamily: theme.typography.fonts.circularStdBold,
    color: theme.colors.typography.link,
    fontWeight: theme.typography.fontWeights.bold,
    fontSize: theme.typography.fontSizes.md,
    lineHeight: theme.typography.lineHeights.xl,
  },
};
