export default {
  API_LOADING_START: 'API_LOADING_START',
  API_LOADING_STOP: 'API_LOADING_STOP',
  IS_INTERNET_CONNECTED: 'IS_INTERNET_CONNECTED',
  UPDATE_SHOW_NET_WORK_MODAL: 'UPDATE_SHOW_NET_WORK_MODAL',
  ON_ERROR_RECEIVED: 'ON_ERROR_RECEIVED',
  NOTIFICATION_COUNT: 'NOTIFICATION_COUNT',
  USER_DETAIL: 'USER_DETAIL',
  USER_PROFILE: 'USER_PROFILE',
  MEMBER_REGISTER:'MEMBER_REGISTER'
};
