export const CONVERSATION = {
  LIMIT: 30,
  USER_ID: '48200',
  CONVERSATION_MODE: 'BOT',
  USER_STATUS: {ONLINE: 'online'},
  CLOSED_MESSAGE_TYPE: 2,
  OPEN_MESSAGE_TYPE: 1,
  YOU: 0,
  ASSIGNED: 1,
  UNASSIGNED: 2,
  CLOSE: 3,
};
