export const accountList = [
  {
    label: 'ACML',
  },
  {
    label: 'Active 2',
  },
  {
    label: 'Active 4',
  },
  {
    label: 'Active 2',
  },
  {
    label: 'Active 1',
  },
  {
    label: 'Active 23',
  },
  {
    label: 'Active 1',
  },
];

export const languageList = [
  {
    code: 'al',
    unicode: 'U+1F1E6 U+1F1F1',
    name: 'Albania',
    tempT: 'Albanian',
    emoji: '🇦🇱',
    languageName: 'Albanian',
    surveyCode: 'sq',
  },
  {
    code: 'bg',
    unicode: 'U+1F1E7 U+1F1EC',
    name: 'Bulgaria',
    tempT: 'Bulgarian',
    emoji: '🇧🇬',
    languageName: 'Bulgarian',
    surveyCode: 'bg',
  },
  {
    code: 'cz',
    unicode: 'U+1F1E8 U+1F1FF',
    name: 'Czechia',
    tempT: 'Czech',
    emoji: '🇨🇿',
    languageName: 'Czech',
    surveyCode: 'cs',
  },
  {
    code: 'en',
    unicode: 'U+1F1EC U+1F1E7',
    name: 'United Kingdom',
    tempT: 'English',
    emoji: '🇬🇧',
    languageName: 'English',
    surveyCode: 'en',
  },
  {
    code: 'ee',
    unicode: 'U+1F1EA U+1F1EA',
    name: 'Estonia',
    tempT: 'Estonian',
    emoji: '🇪🇪',
    languageName: 'Estonian',
    surveyCode: 'et',
  },
  {
    code: 'fr',
    unicode: 'U+1F1EB U+1F1F7',
    name: 'France',
    tempT: 'French',
    emoji: '🇫🇷',
    languageName: 'French',
    surveyCode: 'fr',
  },
  {
    code: 'hi',
    unicode: 'U+1F1EE U+1F1F3',
    name: 'India',
    tempT: 'Hindi',
    emoji: '🇮🇳',
    languageName: 'Hindi',
    surveyCode: 'hi',
  },
  {
    code: 'hu',
    unicode: 'U+1F1ED U+1F1FA',
    name: 'Hungary',
    emoji: '🇭🇺',
    languageName: 'Hungarian',
    surveyCode: 'hu',
  },
  {
    code: 'it',
    unicode: 'U+1F1EE U+1F1F9',
    name: 'Italy',
    tempT: 'Italian',
    emoji: '🇮🇹',
    languageName: 'Italian',
    surveyCode: 'it',
  },
  {
    code: 'lv',
    unicode: 'U+1F1F1 U+1F1FB',
    name: 'Latvia',
    tempT: 'Latvian',
    emoji: '🇱🇻',
    languageName: 'Latvian',
    surveyCode: 'lv',
  },
  {
    code: 'lt',
    unicode: 'U+1F1F1 U+1F1F9',
    name: 'Lithuania',
    tempT: 'Lithuanian',
    emoji: '🇱🇹',
    languageName: 'Lithuanian',
    surveyCode: 'lt',
  },
  {
    code: 'np',
    unicode: 'U+1F1F3 U+1F1F5',
    name: 'Nepal',
    tempT: 'Nepali',
    emoji: '🇳🇵',
    languageName: 'Nepali',
    surveyCode: 'ne',
  },
  {
    code: 'pl',
    unicode: 'U+1F1F5 U+1F1F1',
    name: 'Poland',
    tempT: 'Polish',
    emoji: '🇵🇱',
    languageName: 'Polish',
    surveyCode: 'pl',
  },
  {
    code: 'pt',
    unicode: 'U+1F1F5 U+1F1F9',
    name: 'Portugal',
    tempT: 'Portuguese',
    emoji: '🇵🇹',
    languageName: 'Portuguese',
    surveyCode: 'pt',
  },
  {
    code: 'ro',
    unicode: 'U+1F1F7 U+1F1F4',
    name: 'Romania',
    tempT: 'Romanian',
    emoji: '🇷🇴',
    languageName: 'Romanian',
    surveyCode: 'ro',
  },
  {
    code: 'si',
    unicode: 'U+1F1F8 U+1F1F0',
    name: 'Slovakia',
    tempT: 'Slovak',
    emoji: '🇸🇰',
    languageName: 'Slovak',
    surveyCode: 'sk',
  },
  {
    code: 'sk',
    unicode: 'U+1F1F8 U+1F1EE',
    name: 'Slovenia',
    tempT: 'Slovanian',
    emoji: '🇸🇮',
    languageName: 'Slovanian',
    surveyCode: 'sl',
  },
  {
    code: 'es',
    unicode: 'U+1F1EA U+1F1F8',
    name: 'Spain',
    tempT: 'Spanish',
    emoji: '🇪🇸',
    languageName: 'Spanish',
    surveyCode: 'es',
  },
  {
    code: 'er',
    unicode: 'U+1F1EA U+1F1F7',
    name: 'Eritrea',
    tempT: 'Tigrinya',
    emoji: '🇪🇷',
    languageName: 'Tigrinya',
    surveyCode: 'en',
  },
  {
    code: 'ukr',
    unicode: 'U+1F1FA U+1F1E6',
    name: 'Ukraine',
    emoji: '🇺🇦',
    languageName: 'Ukrainian',
    surveyCode: 'uk',
  },
  {
    code: 'pk',
    unicode: 'U+1F1F5 U+1F1F0',
    name: 'Pakistan',
    tempT: 'Urdu',
    emoji: '🇵🇰',
    languageName: 'Urdu',
    surveyCode: 'ur',
  },
];
